import { useCallback, useEffect, useRef, useState } from 'react'
import { FilesetResolver, HandLandmarker } from '@mediapipe/tasks-vision'

const MODEL='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const url=path=>`${API}${path}`
const LINKS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]]
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value))
const toAngle=(value,inMin,inMax,outMin,outMax)=>Math.round(outMin+(clamp(value,inMin,inMax)-inMin)*(outMax-outMin)/(inMax-inMin))

const TEXT={
 bn:{title:'বিশ্বব্যাপী যোগাযোগে রোবটিক আর্ম',subtitle:'MediaPipe finger command ও manual servo control',camera:'হ্যান্ড ট্র্যাকিং ক্যামেরা',cameraHint:'একটি হাত ক্যামেরার সামনে দেখান',start:'ক্যামেরা চালু করুন',stop:'ক্যামেরা বন্ধ করুন',noHand:'কোনো হাত পাওয়া যায়নি',detected:'শনাক্ত হয়েছে',remote:'ESP32-CAM পর্যবেক্ষণ',manual:'ম্যানুয়াল সার্ভো কন্ট্রোল',move:'সার্ভো চালান',settings:'সেটিংস',save:'সংরক্ষণ',offline:'অফলাইন',waiting:'ক্যামেরা বন্ধ আছে',guide:'ফিঙ্গার কমান্ড',base:'বেস',shoulder:'শোল্ডার',elbow:'এলবো'},
 en:{title:'Worldwide Robotic Arm Communication',subtitle:'MediaPipe finger commands and manual servo control',camera:'Hand-tracking camera',cameraHint:'Show one hand clearly to the camera',start:'Start camera',stop:'Stop camera',noHand:'No hand detected',detected:'Detected',remote:'ESP32-CAM monitor',manual:'Manual servo control',move:'Move servos',settings:'Settings',save:'Save',offline:'Offline',waiting:'Camera is off',guide:'Finger commands',base:'Base',shoulder:'Shoulder',elbow:'Elbow'}
}

function fingers(points,handedness){const result=[handedness==='Right'?Number(points[4].x<points[3].x):Number(points[4].x>points[3].x)];for(const [tip,pip] of [[8,6],[12,10],[16,14],[20,18]])result.push(Number(points[tip].y<points[pip].y));return result}
function paint(canvas,video,points){const w=video.videoWidth,h=video.videoHeight;if(!w||!h)return;canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.save();c.translate(w,0);c.scale(-1,1);c.drawImage(video,0,0);if(points){c.strokeStyle='#8cff66';c.lineWidth=4;for(const[a,b]of LINKS){c.beginPath();c.moveTo(points[a].x*w,points[a].y*h);c.lineTo(points[b].x*w,points[b].y*h);c.stroke()}c.fillStyle='#fff';for(const p of points){c.beginPath();c.arc(p.x*w,p.y*h,4,0,Math.PI*2);c.fill()}}c.restore()}
const Status=({on,children})=><span className={`status ${on?'on':''}`}><i/>{children}</span>

export default function App(){
 const video=useRef(null),canvas=useRef(null),landmarker=useRef(null),frame=useRef(0),active=useRef(false),lastSent=useRef(0)
 const filteredPoint=useRef(null),lastTrackAngles=useRef({base:90,shoulder:90,elbow:90}),trackingBusy=useRef(false)
 const [language,setLanguage]=useState(()=>localStorage.getItem('language')||'bn'),t=TEXT[language]
 const [running,setRunning]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[count,setCount]=useState(0),[hasHand,setHasHand]=useState(false)
 const [controller,setController]=useState(false),[camera,setCamera]=useState(false),[camTick,setCamTick]=useState(0),[settings,setSettings]=useState(false)
 const [angles,setAngles]=useState({base:90,shoulder:90,elbow:90}),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [controllerUrl,setControllerUrl]=useState(()=>localStorage.getItem('controllerUrl')||'http://192.168.0.40')

 const sendTracking=useCallback(async next=>{if(trackingBusy.current)return;trackingBusy.current=true;try{const q=new URLSearchParams({controller:controllerUrl,...Object.fromEntries(Object.entries(next).map(([k,v])=>[k,String(v)]))});const r=await fetch(url(`/api/servo?${q}`),{signal:AbortSignal.timeout(2500)});setController(r.ok)}catch{setController(false)}finally{trackingBusy.current=false}},[controllerUrl])
 const process=useCallback((result,now)=>{const points=result.landmarks?.[0];paint(canvas.current,video.current,points);setHasHand(Boolean(points));if(!points){filteredPoint.current=null;return}const pattern=fingers(points,result.handednesses?.[0]?.[0]?.categoryName||'Right');setCount(pattern.reduce((a,b)=>a+b,0));const tip=points[8],thumb=points[4],pinch=Math.hypot(tip.x-thumb.x,tip.y-thumb.y);const raw={x:tip.x,y:tip.y,pinch};const old=filteredPoint.current||raw;const alpha=.18;const smooth={x:old.x+(raw.x-old.x)*alpha,y:old.y+(raw.y-old.y)*alpha,pinch:old.pinch+(raw.pinch-old.pinch)*alpha};filteredPoint.current=smooth;const next={base:toAngle(smooth.x,.08,.92,170,10),shoulder:toAngle(smooth.y,.08,.92,25,155),elbow:toAngle(smooth.pinch,.03,.25,30,150)};const previous=lastTrackAngles.current;const changed=Object.keys(next).some(key=>Math.abs(next[key]-previous[key])>=3);if(changed&&now-lastSent.current>=140){lastSent.current=now;lastTrackAngles.current=next;setAngles(next);sendTracking(next)}},[sendTracking])

 async function start(){setLoading(true);setError('');try{if(!window.isSecureContext)throw new Error('HTTPS অথবা localhost প্রয়োজন');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.current.srcObject=stream;await video.current.play();const vision=await FilesetResolver.forVisionTasks(WASM);const options=delegate=>({baseOptions:{modelAssetPath:MODEL,...(delegate?{delegate}:{})},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.5,minHandPresenceConfidence:.5,minTrackingConfidence:.5});try{landmarker.current=await HandLandmarker.createFromOptions(vision,options('GPU'))}catch{landmarker.current=await HandLandmarker.createFromOptions(vision,options())}active.current=true;setRunning(true);const loop=now=>{if(!active.current)return;try{if(video.current.readyState>=2)process(landmarker.current.detectForVideo(video.current,now),now)}catch(e){setError(e.message);stop();return}frame.current=requestAnimationFrame(loop)};frame.current=requestAnimationFrame(loop)}catch(e){setError(e.message||'MediaPipe চালু হয়নি');video.current?.srcObject?.getTracks().forEach(x=>x.stop())}finally{setLoading(false)}}
 function stop(){active.current=false;cancelAnimationFrame(frame.current);video.current?.srcObject?.getTracks().forEach(x=>x.stop());setRunning(false);setHasHand(false);filteredPoint.current=null}
 async function move(){setBusy(true);setMessage('Sending…');try{const q=new URLSearchParams({controller:controllerUrl,...Object.fromEntries(Object.entries(angles).map(([k,v])=>[k,String(v)]))});const r=await fetch(url(`/api/servo?${q}`),{signal:AbortSignal.timeout(9000)});if(!r.ok)throw new Error();setController(true);setMessage('Movement complete')}catch{setController(false);setMessage('Controller not responding')}finally{setBusy(false)}}
 function save(e){e.preventDefault();localStorage.setItem('controllerUrl',controllerUrl);setSettings(false)}
 function toggleLanguage(){const next=language==='bn'?'en':'bn';setLanguage(next);localStorage.setItem('language',next);document.documentElement.lang=next}

 useEffect(()=>{const check=async()=>{try{const q=new URLSearchParams({controller:controllerUrl});const r=await fetch(url(`/api/device-status?${q}`),{signal:AbortSignal.timeout(2200),cache:'no-store'});setController(Boolean((await r.json()).online))}catch{setController(false)}};check();const id=setInterval(check,3500);return()=>clearInterval(id)},[controllerUrl])
 useEffect(()=>{const check=async()=>{try{const r=await fetch(url('/api/camera-status'),{cache:'no-store'});const d=await r.json();setCamera(Boolean(d.online));if(d.online)setCamTick(Date.now())}catch{setCamera(false)}};check();const id=setInterval(check,700);return()=>clearInterval(id)},[])
 useEffect(()=>()=>{active.current=false;cancelAnimationFrame(frame.current);video.current?.srcObject?.getTracks().forEach(x=>x.stop());landmarker.current?.close()},[])

 return <div className="app">
  <header><div><p className="eyebrow">WORLDWIDE COMMUNICATION · 3-DOF</p><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="header-actions"><button className="ghost" onClick={toggleLanguage}>{language==='bn'?'English':'বাংলা'}</button><button className="ghost" onClick={()=>setSettings(v=>!v)}>⚙ {t.settings}</button></div></header>
  {settings&&<form className="settings" onSubmit={save}><label>ESP controller URL<input value={controllerUrl} onChange={e=>setControllerUrl(e.target.value)}/></label><button>{t.save}</button></form>}
  {error&&<div className="alert">{error}</div>}
  <section className="statusbar"><Status on={controller}>ESP CONTROLLER {controller?'ONLINE':'OFFLINE'}</Status><Status on={camera}>ESP32-CAM {camera?'ONLINE':'OFFLINE'}</Status><Status on={running}>MEDIAPIPE {running?'LIVE':'OFFLINE'}</Status></section>
  <main>
   <article className="card"><div className="card-head"><div><small>01 · MEDIAPIPE</small><h2>{t.camera}</h2><p>{t.cameraHint}</p></div><div className="counter"><span>{t.detected}</span><b>{hasHand?count:'—'}</b><small>{hasHand?'FINGERS':t.noHand}</small></div></div><div className="viewport"><video ref={video} muted playsInline/><canvas ref={canvas}/>{!running&&<div className="empty"><b>✋</b><span>{t.waiting}</span></div>}</div><div className="card-actions">{running?<button className="danger" onClick={stop}>{t.stop}</button>:<button onClick={start} disabled={loading}>{loading?'MediaPipe loading…':t.start}</button>}</div></article>
   <article className="card"><div className="card-head"><div><small>02 · VISUAL FEEDBACK</small><h2>{t.remote}</h2><p>Remote workspace live view</p></div><Status on={camera}>{camera?'LIVE':t.offline}</Status></div><div className="viewport">{camera?<img src={url(`/api/camera-frame?t=${camTick}`)} alt="ESP32-CAM"/>:<div className="empty"><b>◎</b><span>ESP32-CAM {t.offline}</span></div>}</div><div className="card-actions camera-meta"><span>Automatic MQTT connection</span><Status on={camera}>{camera?'STREAMING':'WAITING'}</Status></div></article>
  </main>
  <section className="commands"><div><small>03 · {t.guide.toUpperCase()}</small><h2>{t.guide}</h2></div><div className="command-grid"><span><b>✊ + ←</b>Base 0°</span><span><b>✊ + →</b>Base 180°</span><span><b>☝</b>Shoulder 90°</span><span><b>✌</b>Shoulder 40°</span><span><b>💍</b>Elbow 0°</span><span><b>🤙</b>Elbow 140°</span><span><b>🖐</b>Home 90°</span></div></section>
  <section className="manual"><div className="manual-head"><div><small>04 · MANUAL MODE</small><h2>{t.manual}</h2></div><Status on={controller}>{controller?'CONNECTED':t.offline}</Status></div><div className="sliders">{[['base',t.base],['shoulder',t.shoulder],['elbow',t.elbow]].map(([key,label])=><label key={key}><span><b>{label}</b><output>{angles[key]}°</output></span><input type="range" min="0" max="180" value={angles[key]} onChange={e=>setAngles(a=>({...a,[key]:Number(e.target.value)}))}/></label>)}</div><div className="manual-actions"><span>{message}</span><button onClick={move} disabled={busy}>{busy?'Moving…':t.move}</button></div></section>
  <footer>MD. MAHFUZUR RAHMAN <span>·</span> MediaPipe <span>·</span> ESP Robotic Arm</footer>
 </div>
}
