import { useCallback, useEffect, useRef, useState } from 'react'
import { FilesetResolver, HandLandmarker } from '@mediapipe/tasks-vision'

const MODEL='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const url=p=>`${API}${p}`
const LINKS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]]

function draw(canvas,video,pts){const w=video.videoWidth,h=video.videoHeight;if(!w||!h)return;canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.save();c.translate(w,0);c.scale(-1,1);c.drawImage(video,0,0);if(pts){c.strokeStyle='#9dfb53';c.lineWidth=3;LINKS.forEach(([a,b])=>{c.beginPath();c.moveTo(pts[a].x*w,pts[a].y*h);c.lineTo(pts[b].x*w,pts[b].y*h);c.stroke()});c.fillStyle='#f4ffdf';pts.forEach(p=>{c.beginPath();c.arc(p.x*w,p.y*h,4,0,Math.PI*2);c.fill()})}c.restore()}
function estimate(p){if(!p)return null;const palm=Math.hypot(p[5].x-p[17].x,p[5].y-p[17].y);return{x:Math.round((.5-p[0].x)*48),y:Math.round((.72-p[0].y)*42),z:Math.round(Math.min(36,Math.max(10,4.6/Math.max(palm,.04))))}}
const Pill=({active,children})=><span className={`pill ${active?'active':''}`}><i/>{children}</span>
const Metric=({value,label,unit=''})=><div className="metric"><strong>{value}<small>{unit}</small></strong><span>{label}</span></div>

export default function App(){
 const video=useRef(null),canvas=useRef(null),detector=useRef(null),raf=useRef(0),live=useRef(false),frames=useRef({n:0,t:0})
 const [running,setRunning]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[hand,setHand]=useState(false)
 const [target,setTarget]=useState({x:0,y:0,z:0}),[fps,setFps]=useState(0),[confidence,setConfidence]=useState(0)
 const [controller,setController]=useState(false),[camera,setCamera]=useState(false),[camTick,setCamTick]=useState(0)
 const [angles,setAngles]=useState({base:90,shoulder:90,elbow:90}),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [language,setLanguage]=useState(()=>localStorage.getItem('researchLanguage')||'bn')
 function toggleLanguage(){const next=language==='bn'?'en':'bn';setLanguage(next);localStorage.setItem('researchLanguage',next);document.documentElement.lang=next}
 const controllerUrl=useRef(localStorage.getItem('controllerUrl')||'http://192.168.0.40')
 const process=useCallback((result,now)=>{const p=result.landmarks?.[0];draw(canvas.current,video.current,p);setHand(Boolean(p));if(p){setTarget(estimate(p));setConfidence(Math.round((result.handednesses?.[0]?.[0]?.score||0)*100))}frames.current.n++;if(now-frames.current.t>600){setFps(Math.round(frames.current.n*1000/(now-frames.current.t||1000)));frames.current={n:0,t:now}}},[])
 async function start(){
  setLoading(true);setError('')
  try{
   if(!window.isSecureContext)throw new Error('Camera চালাতে HTTPS অথবা localhost প্রয়োজন।')
   if(!navigator.mediaDevices?.getUserMedia)throw new Error('এই browser camera access support করে না। Chrome/Edge ব্যবহার করুন।')
   const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false})
   video.current.srcObject=stream;await video.current.play()
   const vision=await FilesetResolver.forVisionTasks(WASM);detector.current?.close()
   const options=delegate=>({baseOptions:{modelAssetPath:MODEL,...(delegate?{delegate}:{})},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.5,minHandPresenceConfidence:.5,minTrackingConfidence:.5})
   try{detector.current=await HandLandmarker.createFromOptions(vision,options('GPU'))}
   catch{detector.current=await HandLandmarker.createFromOptions(vision,options())}
   live.current=true;setRunning(true);frames.current={n:0,t:performance.now()}
   const loop=now=>{
    if(!live.current)return
    try{if(video.current.readyState>=2)process(detector.current.detectForVideo(video.current,now),now)}
    catch(e){setError(`MediaPipe frame error: ${e.message}`);stop();return}
    raf.current=requestAnimationFrame(loop)
   }
   raf.current=requestAnimationFrame(loop)
  }catch(e){video.current?.srcObject?.getTracks().forEach(t=>t.stop());setError(`MediaPipe চালু হয়নি: ${e.message||'Unknown error'}`)}
  finally{setLoading(false)}
 }
 function stop(){live.current=false;cancelAnimationFrame(raf.current);video.current?.srcObject?.getTracks().forEach(t=>t.stop());setRunning(false);setHand(false);setFps(0)}
 async function move(){setBusy(true);setMessage('Command পাঠানো হচ্ছে…');try{const q=new URLSearchParams({controller:controllerUrl.current,...Object.fromEntries(Object.entries(angles).map(([k,v])=>[k,String(v)]))});const r=await fetch(url(`/api/servo?${q}`),{signal:AbortSignal.timeout(9000)});if(!r.ok)throw new Error();setController(true);setMessage('Position command সম্পন্ন হয়েছে')}catch{setController(false);setMessage('Controller সাড়া দিচ্ছে না')}finally{setBusy(false)}}
 useEffect(()=>{const check=async()=>{try{const q=new URLSearchParams({controller:controllerUrl.current});const r=await fetch(url(`/api/device-status?${q}`),{signal:AbortSignal.timeout(2200),cache:'no-store'});setController(Boolean((await r.json()).online))}catch{setController(false)}};check();const id=setInterval(check,3500);return()=>clearInterval(id)},[])
 useEffect(()=>{const check=async()=>{try{const r=await fetch(url('/api/camera-status'),{cache:'no-store'});const d=await r.json();setCamera(Boolean(d.online));if(d.online)setCamTick(Date.now())}catch{setCamera(false)}};check();const id=setInterval(check,700);return()=>clearInterval(id)},[])
 useEffect(()=>()=>{live.current=false;cancelAnimationFrame(raf.current);video.current?.srcObject?.getTracks().forEach(t=>t.stop());detector.current?.close()},[])
 useEffect(()=>{
  const english={
   'হাতের ইশারায়':'Control by hand,','নিরাপদ রোবটিক নিয়ন্ত্রণ।':'safe and intuitive.',
   'Mobile Web MediaPipe, monocular 3D position estimation এবং latency-aware adaptive scaling ব্যবহার করে rotating-base 3-DOF robotic arm teleoperation framework.':'A low-cost, rotating-base 3-DOF robotic-arm teleoperation framework using Mobile Web MediaPipe, monocular 3D position estimation, and latency-aware adaptive scaling.',
   'Adaptive scaling ও latency compensation কি fixed mapping-এর তুলনায় accuracy এবং safety উন্নত করে?':'Do adaptive scaling and latency compensation improve accuracy and safety compared with fixed mapping?',
   'একটি হাত থেকে':'From one hand to','একটি নিরাপদ trajectory.':'one safe trajectory.',
   'প্রতিটি frame-কে calibrated Cartesian target-এ রূপান্তর করা হয়। IK solver rotating base, shoulder ও elbow-এর joint limit মেনে angle তৈরি করে; safety layer tracking হারালে motion বন্ধ করে।':'Each frame is converted into a calibrated Cartesian target. The IK solver respects the rotating base, shoulder and elbow limits; the safety layer stops motion if tracking is lost.',
   'MediaPipe-এর 21 landmark থেকে wrist position ও palm width.':'Wrist position and palm width from 21 MediaPipe landmarks.','Calibrated palm scale দিয়ে camera-relative X, Y, Z.':'Camera-relative X, Y and Z from a calibrated palm scale.','Distance, velocity, confidence ও latency থেকে dynamic gain.':'Dynamic gain from distance, velocity, confidence and latency.','Workspace clamp এবং base–shoulder–elbow 3-DOF inverse kinematics.':'Workspace clamping and base–shoulder–elbow 3-DOF inverse kinematics.','ESP controller-এ timestamped command; ESP32-CAM feedback.':'Timestamped commands to the ESP controller with ESP32-CAM feedback.',
   'Target-এর কাছে ধীর,':'Slower near the target,','খোলা পথে দ্রুত।':'faster in open space.',
   'Baseline বনাম proposed method.':'Baseline versus proposed method.','একই participant প্রতিটি condition-এ reaching ও pick-and-place task সম্পন্ন করবে।':'Each participant completes reaching and pick-and-place tasks under every condition.',
   'Camera stream অপেক্ষমাণ':'Waiting for camera stream','HTTPS permission প্রয়োজন':'HTTPS permission required','ESP32-CAM সংযোগ নেই':'ESP32-CAM is not connected',
   'এটি monocular calibrated estimate; experiment-এর আগে ground-truth distance দিয়ে calibration করতে হবে।':'This is a monocular calibrated estimate; calibrate it against ground-truth distances before the experiment.',
   'Engineering project থেকে':'From engineering project to','publishable evidence.':'publishable evidence.',
   'Adaptive + compensated control endpoint error ও overshoot কমাবে।':'Adaptive and compensated control will reduce endpoint error and overshoot.','Reaching, pick-and-place ও workspace-boundary task; controlled latency levels.':'Reaching, pick-and-place and workspace-boundary tasks under controlled latency levels.','Trajectory, error, time, success, jitter এবং safety event automatic logging.':'Automatic logging of trajectory, error, time, success, jitter and safety events.','Repeated-measures statistical comparison এবং effect-size reporting.':'Repeated-measures statistical comparison with effect-size reporting.'
  }
  const nodes=[];const walker=document.createTreeWalker(document.querySelector('.site'),NodeFilter.SHOW_TEXT);while(walker.nextNode())nodes.push(walker.currentNode)
  nodes.forEach(node=>{const original=node.parentElement?.dataset?.bnText||node.nodeValue;if(node.parentElement&&!node.parentElement.dataset.bnText)node.parentElement.dataset.bnText=original;node.nodeValue=language==='en'?(english[original]||original):original})
 },[language])
 useEffect(()=>{document.title='Worldwide Communication · 3-DOF Vision-Controlled Robotic Arm';const heading=document.querySelector('.hero .kicker');if(heading)heading.textContent='WORLDWIDE COMMUNICATION · 3-DOF TELEOPERATION'},[language])
 return <div className="site">
  <nav><a className="brand" href="#top"><span>R³</span><b>HAND//ARM LAB</b></a><div className="navlinks"><a href="#method">Method</a><a href="#experiment">Experiment</a><a href="#prototype">Prototype</a></div><div className="nav-actions"><button type="button" className="language-toggle" onClick={toggleLanguage} aria-label="Switch between Bangla and English"><b>{language==='bn'?'EN':'বাং'}</b><span>{language==='bn'?'English':'বাংলা'}</span></button><Pill active={controller}>{controller?'SYSTEM ONLINE':'LAB MODE'}</Pill></div></nav>
  <header id="top" className="hero"><div className="hero-copy"><p className="kicker">RESEARCH PROTOTYPE · 3-DOF TELEOPERATION</p><h1>হাতের ইশারায়<br/><em>নিরাপদ রোবটিক নিয়ন্ত্রণ।</em></h1><p className="lead">Mobile Web MediaPipe, monocular 3D position estimation এবং latency-aware adaptive scaling ব্যবহার করে rotating-base 3-DOF robotic arm teleoperation framework.</p><div className="hero-actions"><a className="button" href="#prototype">Live prototype</a><a className="text-link" href="#experiment">Research design <span>↗</span></a></div></div><div className="hero-visual"><div className="grid-orbit"/><div className="arm base"/><div className="arm upper"/><div className="joint j1">q₁</div><div className="joint j2">q₂</div><div className="arm fore"/><div className="joint j3">q₃</div><div className="endpoint">●</div><span className="axis ax">X</span><span className="axis ay">Y</span><span className="axis az">Z</span><div className="joint-key"><span>q₁ · ROTATING BASE</span><span>q₂ · SHOULDER</span><span>q₃ · ELBOW</span><b>NO GRIPPER</b></div><div className="visual-tag"><i/> TARGET POSITION<br/><b>X 18 · Y 24 · Z 31 cm</b></div></div></header>
  <section className="summary-strip"><div><small>RESEARCH QUESTION</small><p>Adaptive scaling ও latency compensation কি fixed mapping-এর তুলনায় accuracy এবং safety উন্নত করে?</p></div><Metric value="03" label="ARM DOF"/><Metric value="21" label="HAND LANDMARKS"/><Metric value="04" label="TEST CONDITIONS"/></section>
  <section id="method" className="section method"><div className="section-intro"><p className="kicker">01 · PROPOSED METHOD</p><h2>একটি হাত থেকে<br/>একটি নিরাপদ trajectory.</h2><p>প্রতিটি frame-কে calibrated Cartesian target-এ রূপান্তর করা হয়। IK solver rotating base, shoulder ও elbow-এর joint limit মেনে angle তৈরি করে; safety layer tracking হারালে motion বন্ধ করে।</p></div><div className="pipeline">{[['01','PERCEPTION','MediaPipe-এর 21 landmark থেকে wrist position ও palm width.'],['02','3D ESTIMATION','Calibrated palm scale দিয়ে camera-relative X, Y, Z.'],['03','ADAPTIVE CONTROL','Distance, velocity, confidence ও latency থেকে dynamic gain.'],['04','SAFE IK','Workspace clamp এবং base–shoulder–elbow 3-DOF inverse kinematics.'],['05','EXECUTION','ESP controller-এ timestamped command; ESP32-CAM feedback.']].map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section className="equation-panel"><div><p className="kicker">CONTROL LAW</p><h2>Target-এর কাছে ধীর,<br/>খোলা পথে দ্রুত।</h2></div><div className="formula"><span>s(t) = s<sub>min</sub> + (s<sub>max</sub> − s<sub>min</sub>)</span><b>g(d) · g(v) · g(L) · g(c)</b></div><div className="legend"><span><i style={{'--c':'#9dfb53'}}/>d · target distance</span><span><i style={{'--c':'#7dd3fc'}}/>v · hand velocity</span><span><i style={{'--c':'#f9a8d4'}}/>L · network latency</span><span><i style={{'--c':'#fde68a'}}/>c · tracking confidence</span></div></section>
  <section id="experiment" className="section experiment"><div className="section-title"><p className="kicker">02 · EXPERIMENTAL DESIGN</p><h2>Baseline বনাম proposed method.</h2><p>একই participant প্রতিটি condition-এ reaching ও pick-and-place task সম্পন্ন করবে।</p></div><div className="conditions"><div className="table-head"><span>CONDITION</span><span>SCALING</span><span>COMPENSATION</span><span>SAFETY</span></div>{[['C1 · Baseline','Fixed','—','Hard limit'],['C2','Adaptive','—','Hard limit'],['C3','Fixed','Latency-aware','Hard limit'],['C4 · Proposed','Adaptive','Latency-aware','Soft workspace']].map((r,i)=><div className={i===3?'featured':''} key={r[0]}>{r.map((x,j)=><span key={x}>{j===0&&i===3?<b>★</b>:null}{x}</span>)}</div>)}</div><div className="metrics-row">{[['cm','Endpoint error'],['sec','Completion time'],['%','Success rate'],['ms','End-to-end latency'],['#','Safety violations']].map(([u,l])=><div key={l}><strong>{u}</strong><span>{l}</span></div>)}</div></section>
  <section id="prototype" className="prototype"><div className="prototype-head"><div><p className="kicker">03 · LIVE PROTOTYPE</p><h2>Tracking &amp; control console</h2></div><div className="status-row"><Pill active={running}>{running?'MEDIAPIPE LIVE':'CAMERA OFF'}</Pill><Pill active={controller}>ESP CONTROLLER</Pill><Pill active={camera}>ESP32-CAM</Pill></div></div>{error&&<div className="alert">{error}</div>}<div className="console-grid"><div className="feed-card"><div className="feed-title"><span>OPERATOR CAMERA</span><span>{fps||'--'} FPS</span></div><div className="viewport"><video ref={video} muted playsInline/><canvas ref={canvas}/>{!running&&<div className="feed-empty"><div>+</div><p>Camera stream অপেক্ষমাণ</p></div>}<div className="reticle"/></div><div className="feed-controls">{running?<button className="button stop" onClick={stop}>Stop tracking</button>:<button className="button" onClick={start} disabled={loading}>{loading?'Model loading…':'Start hand tracking'}</button>}<span>HTTPS permission প্রয়োজন</span></div></div><div className="telemetry"><p className="kicker">LIVE TELEMETRY</p><Metric value={hand?'TRACKED':'—'} label="HAND STATE"/><div className="xyz"><div><span>X</span><b>{target.x}</b><small>cm</small></div><div><span>Y</span><b>{target.y}</b><small>cm</small></div><div><span>Z</span><b>{target.z}</b><small>cm</small></div></div><div className="confidence"><span>TRACKING CONFIDENCE <b>{confidence}%</b></span><i><u style={{width:`${confidence}%`}}/></i></div><p className="note">এটি monocular calibrated estimate; experiment-এর আগে ground-truth distance দিয়ে calibration করতে হবে।</p></div><div className="feed-card remote"><div className="feed-title"><span>REMOTE FEEDBACK</span><span>{camera?'LIVE':'OFFLINE'}</span></div><div className="viewport">{camera?<img src={url(`/api/camera-frame?t=${camTick}`)} alt="ESP32-CAM feedback"/>:<div className="feed-empty"><div>⌾</div><p>ESP32-CAM সংযোগ নেই</p></div>}</div><div className="feed-controls"><Pill active={camera}>{camera?'VISUAL LINK':'WAITING'}</Pill><span>Timestamped remote view</span></div></div></div><div className="manual"><div><p className="kicker">MANUAL VALIDATION</p><h3>Joint position test</h3></div><div className="sliders">{[['base','Base · q₁'],['shoulder','Shoulder · q₂'],['elbow','Elbow · q₃']].map(([key,label])=><label key={key}><span>{label}<b>{angles[key]}°</b></span><input type="range" min="0" max="180" value={angles[key]} onChange={e=>setAngles(a=>({...a,[key]:Number(e.target.value)}))}/></label>)}</div><div className="manual-action"><small>{message||'Joint limits: 0°—180°'}</small><button className="button" onClick={move} disabled={busy}>{busy?'Sending…':'Send joint command'}</button></div></div></section>
  <section className="paper"><div><p className="kicker">PAPER BLUEPRINT</p><h2>Engineering project থেকে<br/><em>publishable evidence.</em></h2></div><ol>{[['01','Hypothesis','Adaptive + compensated control endpoint error ও overshoot কমাবে।'],['02','Protocol','Reaching, pick-and-place ও workspace-boundary task; controlled latency levels.'],['03','Evidence','Trajectory, error, time, success, jitter এবং safety event automatic logging.'],['04','Analysis','Repeated-measures statistical comparison এবং effect-size reporting.']].map(([n,t,d])=><li key={n}><span>{n}</span><p><b>{t}</b>{d}</p></li>)}</ol></section>
  <footer><div className="brand"><span>R³</span><b>HAND//ARM LAB</b></div><p>Mobile vision research prototype · rotating-base 3-DOF · no gripper</p><p>MD. MAHFUZUR RAHMAN · 2026</p></footer>
 </div>
}
